# １-１. 確率・統計 (Statistics)

**問１**

空欄 （あ）、（い）に埋まる言葉として正しいものを選べ。  　　
コイン投げにおいて、表の確率を $p$、裏の確率を $q = 1-p$ とする。
このとき、表裏が等確率で出現する真の分布 $P=(0.5,0.5)$ と、予測分布 $Q=(p,1-p)$ とのクロスエントロピーを考える。　　
このとき、クロスエントロピーを最小化するような $p$ は（あ）であり、そのときのクロスエントロピーの値は（い）となる。  
A.（あ）0.5、（い）0.5  
B.（あ）0.75、（い）1.0  
C. （あ）0.5、（い）1.0  
D. （あ）0.8、（い）0.5  


**問１**

KLダイバージェンス $D_{KL}(P||Q)$ と交差エントロピー H(P,Q) の関係式は以下のように表される。  
$$
D_{KL}(P||Q) = H(P,Q) - H(P)
$$

ここで、P は真の分布、Q は予測分布、H(P)はPのエントロピーである。
この関係に関する説明として正しくないものはどれか。  

A. 交差エントロピー損失を最小化することは、予測分布Qを真の分布Pに近づけることと等価である。  
B. 真の分布PのエントロピーH(P)は固定値なので、交差エントロピーの最小化はKLダイバージェンスの最小化と等価である。  
C. KLダイバージェンスは常に非負の値を取り、P=Qの時に最小値0となる。  
D. KLダイバージェンスは対称性を持つため、$D_{KL}(P||Q) = D_{KL}(Q||P)$ が常に成立する。  

**問２**

次の文章を読み、空欄に最もよく当てはまる選択肢をそれぞれ1つずつ選べ。  

平均が $\mu$、分散が1の一変量正規分布の確率密度関数は、

$$
f(x; \mu) = \frac{1}{\sqrt{2\pi}} \exp \left( -\frac{1}{2} (x - \mu)^2 \right)
$$

によって与えられる。

このとき、実数値データの集合が $D = \{x_1, x_2, \ldots, x_n\}$ によって与えられる。  
データが平均 $\mu$、分散1の一変量正規分布に独立に従うとして、最大推定法によってパラメータを求める。  

尤度関数 $L(\mu) = (A)$ であることから、パラメータ$\mu$は$(B)$の最小化問題を解くことによって推定が可能である。  
したがって、パラメータの最尤推定量は $\hat{\mu} = (C)$である。  

I: (A)の選択肢

A. $\sum_{i=1}^n f(x_i;\mu)$  
B. $\sum_{i=1}^n \log f(x_i;\mu)$  
C. $\prod_{i=1}^n f(x_i;\mu)$  
D. $\prod_{i=1}^n \log f(x_i;\mu)$  

II: (B)の選択肢

A. $\frac{1}{2} \sum_{i=1}^n (x_i - \mu)^2$  
B. $-\frac{1}{2} \sum_{i=1}^n (x_i - \mu)^2$  
C. $\prod_{i=1}^n (x_i - \mu)^2$  
D. $-\frac{1}{2} \prod_{i=1}^n (x_i - \mu)^2$  

III: (C)の選択肢

A. $\sum_{i=1}^n x_i$  
B. $\frac{1}{n} \sum_{i=1}^n x_i$  
C. $\prod_{i=1}^n x_i$  
D. $\left(\prod_{i=1}^n x_i \right)^{1/n}$  

{{< pagebreak >}}

**問３**

以下の MAP に関する説明について、空欄 （ア）、（イ）に埋まる言葉として正しいものを選べ。
  
MAP推定は Maximum A Posteriori Estimation の略語であり、MLE（Maximum Likelihood Estimation）と比べて、（ア）という特徴がある。  
MAPによって得られるパラメータを $\theta_{\mathrm{MAP}}$ とすると、$\theta_{\mathrm{MAP}}$ は以下の式によって与えられる。  
$$
\theta_{\mathrm{MAP}} = \arg\max_{\theta}\, P(\theta \mid X) \;=\; \text{（イ）}
$$

I:（ア）に入るものを選べ。  

A. MLEは事前分布を考慮しないが、MAPは事前分布を考慮する  
B. MLEは事後分布を最大化するが、MAPは尤度を最大化する  
C. MLEとMAPは常に同じ解を与える  
D. MAPは損失関数として必ず平均二乗誤差を用いる  

II:（イ）に入るものを選べ。  

A. $\arg\max_{\theta}\, P(X \mid \theta)$  
B. $\arg\max_{\theta} \, \dfrac{P(\theta)}{P(X)}$  
C. $\arg\max_{\theta} \, P(X \mid \theta)\, P(\theta)$  
D. $\arg\max_{\theta} \, \log P(X)$  
